### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by OmniCraft500** [Tynoxs/BuildersDelight#12]
I don't know why, but when I try to load the version for 1-19 (v.0.9.5) it says that it has failed to load correctly. I took out the other mods that I have and it still comes up as failed to load correctly. Is there a mod that is required for it to run properly?

**Comment by Yourname942** [comment]
I am also getting this Error:
```
[10:42:55] [Render thread/ERROR]: Failed to load: com.tynoxs.buildersdelight.compat.jei.JeiIntegration
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mezz.jei.forge.startup.ForgePluginFinder.getInstances(ForgePluginFinder.java:47) ~[jei-1.19.2-forge-11.6.0.1015.jar%23765!/:11.6.0.1015]
	at mezz.jei.forge.startup.ForgePluginFinder.getModPlugins(ForgePluginFinder.java:27) ~[jei-1.19.2-forge-11.6.0.1015.jar%23765!/:11.6.0.1015]
	at mezz.jei.forge.JustEnoughItemsClient.onRegisterReloadListenerEvent(JustEnoughItemsClient.java:58) ~[jei-1.19.2-forge-11.6.0.1015.jar%23765!/:11.6.0.1015]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.8.jar%23976!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:306) ~[fmlcore-1.19.2-43.2.8.jar%23975!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.2-43.2.8.jar%23975!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:306) ~[fmlcore-1.19.2-43.2.8.jar%23975!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.m_203704_(NamespacedWrapper.java:55) ~[forge-1.19.2-43.2.8-universal.jar%23979!/:?]
	at net.minecraftforge.registries.NamespacedWrapper.m_203505_(NamespacedWrapper.java:73) ~[forge-1.19.2-43.2.8-universal.jar%23979!/:?]
	at net.minecraft.core.Registry.m_194579_(Registry.java:594) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at net.minecraft.core.Registry.m_122965_(Registry.java:590) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at net.minecraft.world.item.crafting.RecipeType.m_44119_(RecipeType.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23974!/:?]
	at com.tynoxs.buildersdelight.compat.jei.JeiIntegration.<clinit>(JeiIntegration.java:15) ~[BuildersDelight-1.19.2-v.1.1.jar%23624!/:1.1]
	... 30 more
```

Minecraft: 1.19.2
Forge: 43.2.8
JEI: jei-1.19.2-forge-11.6.0.1015
Builder's Delight: BuildersDelight-1.19.2-v.1.1

latest log: https://paste.ee/p/HAMIS

**Comment by Yourname942** [comment]
I have this issue as well
