### ISSUE TITLE
1.19 ResourcePack Incompat

### ISSUE THREAD

**Issue by Speiger** [Tynoxs/BuildersDelight#2]
Since 1.19 resource packs forces ResourceLocations to be used and when you scan for custom files this causes crashes if not every single file is resourcelocation conform.

So we got a crash:
```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: buildersdelight:textures/block/tuff_3 - Kopie.png
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.19-20220607.102129-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.19-20220607.102129-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.resource.PathResourcePack.lambda$getResources$1(PathResourcePack.java:116) ~[forge-1.19-41.0.63-universal.jar%23132!/:?] {re:classloading}
```

Please either remove the texture or make it resourcelocation conform.

**Comment by Tynoxs** [comment]
Whoops. Thank you for reporting.

**Comment by Speiger** [comment]
Thank you for the quick fix.
